#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes
i=1
j=0
while [ "$j" -le 12 ]
do
    echo "Hour: $j"
    i=1
    while [ "$i" -le 59 ]
    do
        echo "$i"
	i=$((i + 1))
    done
    j=$((j + 1))
done
i=$i
